### ISSUE TITLE
MadMax v 0.1.1 to support pools

### ISSUE THREAD

**Issue by Gman2214** [xTheJakalx/SimpleChiaMADMAXPlotterGUI#2]
Any Idea if you will have new release for MadMax v 0.1.1 to support pools ?

**Comment by MarFre22** [comment]
+1

**Comment by xTheJakalx** [comment]
I will look into it and make some changes to support pools, but no ETA on updates though :D

**Comment by Gman2214** [comment]
Okay...Thanks....looking forward to update.

**Comment by xTheJakalx** [comment]
Updated
